# Generated by Django 4.2.7 on 2025-08-02 20:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(help_text="Search query text", max_length=500),
                ),
                (
                    "result_count",
                    models.IntegerField(help_text="Number of results returned"),
                ),
                (
                    "execution_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Query execution time in seconds",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User agent string",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="User IP address", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Search Log",
                "verbose_name_plural": "Search Logs",
                "db_table": "search_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="search_logs_created_1842c5_idx"
                    ),
                    models.Index(
                        fields=["execution_time"], name="search_logs_executi_b7db40_idx"
                    ),
                    models.Index(fields=["query"], name="search_logs_query_5b6409_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Source name (e.g., 'LiveMint')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        help_text="Source domain", max_length=255, unique=True
                    ),
                ),
                (
                    "base_url",
                    models.CharField(help_text="Base URL for scraping", max_length=500),
                ),
                (
                    "scraping_frequency",
                    models.IntegerField(
                        default=3600,
                        help_text="Scraping interval in seconds",
                        validators=[
                            django.core.validators.MinValueValidator(300),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether source is active"
                    ),
                ),
                (
                    "last_scraped_at",
                    models.DateTimeField(
                        blank=True, help_text="Last successful scraping", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "News Source",
                "verbose_name_plural": "News Sources",
                "db_table": "news_sources",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="news_source_is_acti_e04e66_idx"
                    ),
                    models.Index(
                        fields=["last_scraped_at"],
                        name="news_source_last_sc_fccc61_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Original article URL", max_length=2048, unique=True
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Article headline", max_length=500),
                ),
                (
                    "description",
                    models.TextField(help_text="Article summary/description"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated summary (stored after first generation)",
                        null=True,
                    ),
                ),
                ("content", models.TextField(help_text="Full article content")),
                (
                    "published_at",
                    models.DateTimeField(help_text="Original publication date"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_scraped_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Last scraping timestamp"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Soft delete flag"),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Article word count for analytics",
                        null=True,
                    ),
                ),
                (
                    "reading_time",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated reading time in minutes",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Reference to news source",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="news.newssource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "articles",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("list", "List View"),
                            ("detail", "Detail View"),
                            ("summary", "Summary View"),
                        ],
                        help_text="Type of view",
                        max_length=10,
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        help_text="User agent string",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="User IP address", null=True
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Session identifier",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        help_text="Reference to article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="news.article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article View",
                "verbose_name_plural": "Article Views",
                "db_table": "article_views",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["article"], name="article_vie_article_41fada_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="article_vie_created_c0c2e1_idx"
                    ),
                    models.Index(
                        fields=["view_type"], name="article_vie_view_ty_0c1b35_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["published_at"], name="articles_publish_73ad5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["source"], name="articles_source__bca100_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["created_at"], name="articles_created_82e966_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_active"], name="articles_is_acti_1afea8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["title", "description"], name="articles_title_4cd33e_idx"
            ),
        ),
    ]
